import { CommonModule } from '@angular/common';
import { Component, OnInit, WritableSignal, effect, inject, signal } from '@angular/core';
import {
  FormBuilder,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { MatIconModule } from '@angular/material/icon';
import { MatTooltipModule } from '@angular/material/tooltip';
import { ToastrService } from 'ngx-toastr';
import { DatabaseConnectionService, DatabaseConnectionDTO } from '../services/database-connection.service';
import { BUTTON_VISIBILITY, MENU_NAME, ONCLICK_RESET, ONCLICK_SAVE } from '../../../constant/button-signals.constant';
import { environment } from '../../../../../environments/environment';
import { InputTextBox } from '../../../common-components/input-types/input-text-box/input-text-box';
import { InputSelectOptionField } from '../../../common-components/input-types/input-select-option-field/input-select-option-field';
import { InputIdBox } from '../../../common-components/input-types/input-id-box/input-id-box';
import { ExpansionPanelHeader } from '../../../common-components/expansion-panel-header/expansion-panel-header';
import { GenericModal } from '../../../common-components/generic-component-type/generic-modal/generic-modal';
import { AuthService } from '../../../../core/auth/auth.service';
import { UserService } from '../../../../core/user/user.service';


/**
 * Report DB Connection Setup Page
 * Handles CRUD operations for database connection configurations
 */
@Component({
  selector: 'app-report-db-setup-page',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatIconModule,
    MatTooltipModule,
    InputTextBox,
    InputSelectOptionField,
    InputIdBox,
    ExpansionPanelHeader,
    GenericModal
],
  templateUrl: './report-db-setup-ui.html',
  styleUrl: './report-db-setup-ui.scss'
})
export class ReportDbSetupUI implements OnInit {
  // Injected services
  private formBuilder = inject(FormBuilder);
  private toastr = inject(ToastrService);
  private dbService = inject(DatabaseConnectionService);
  private _authService = inject(AuthService);
  private _userService = inject(UserService);

  // Form and state properties
  connectionForm!: FormGroup;
  loading = signal<boolean>(false);
  reportDbPanel: WritableSignal<boolean> = signal(true);

  // Modal properties
  showModal = signal<boolean>(false);
  modalComponent?: any;
  modalComponentData?: any;
  // Database type options with their corresponding drivers
  databaseTypeOptions = [
    { key: 'ORACLE', value: 'Oracle', driver: 'oracle.jdbc.OracleDriver' },
    { key: 'MYSQL', value: 'MySQL', driver: 'com.mysql.cj.jdbc.Driver' },
    { key: 'POSTGRESQL', value: 'PostgreSQL', driver: 'org.postgresql.Driver' },
    { key: 'SQLSERVER', value: 'SQL Server', driver: 'com.microsoft.sqlserver.jdbc.SQLServerDriver' },
  ];

  // Connection list loaded from backend
  connectionList: DatabaseConnectionDTO[] = [];
  menuName = MENU_NAME;
  onClickReset = ONCLICK_RESET;
  onClickSave = ONCLICK_SAVE;

  constructor() {
    effect(() => {
      let localMenuName =  'REPORT DB SETUP';
      this.menuName.set(localMenuName);
    });
    BUTTON_VISIBILITY.set({
      save: true,
      update: false,
      view: false,
      delete: false,
      exit: true,
      reset: true,
    });
    this.setupSignalEffects();
  }

  ngOnInit() {
    this.initializeForm();
    // this.loadConnections();
  }
  private setupSignalEffects(): void {
    effect(() => {
      this.handleButtonActions();
    });
  }

  private handleButtonActions(): void {
    if (this.onClickReset()) {
      this.onRefresh();
    } else if (this.onClickSave()) {
      this.onSave();
    }
  }

  /**
   * Initialize the connection form with validation
   */
  private initializeForm() {
    this.connectionForm = this.formBuilder.group({
      id: [null], // Auto-generated by backend, not editable
      vAppName: ['ultimus', [Validators.required, this.validateAppName]], // Application name
      dbType: ['ORACLE', [Validators.required]], // Database type
      driver: ['oracle.jdbc.OracleDriver', [Validators.required]], // JDBC driver
      host: ['', [Validators.required, Validators.maxLength(200)]], // Host address
      port: ['1521', [Validators.required]], // Port number
      service: ['', [Validators.required, Validators.maxLength(100)]], // Service name
      url: [''], // Auto-generated connection URL
      username: ['', [Validators.required, Validators.maxLength(50)]], // Username
      password: [''], // Password
      connectionName: ['', [Validators.required, Validators.maxLength(100)]], // Display name
      isDefaultConnection: [false],
    });

    // Set up form value changes to auto-generate URL
    this.setupUrlGeneration();
  }

  /**
   * Setup automatic URL generation based on form values
   */
  private setupUrlGeneration() {
    // Watch for changes in host, port, service to auto-generate URL
    this.connectionForm.valueChanges.subscribe(() => {
      this.generateConnectionUrl();
    });

    // Watch for database type changes to set the correct driver
    this.connectionForm.get('dbType')?.valueChanges.subscribe((dbType) => {
      const selectedDb = this.databaseTypeOptions.find(option => option.key === dbType);
      if (selectedDb) {
        this.connectionForm.patchValue({ driver: selectedDb.driver }, { emitEvent: false });
      }
    });
  }

  /**
   * Generate JDBC connection URL based on form values
   */
  private generateConnectionUrl() {
    const dbType = this.connectionForm.get('dbType')?.value;
    const host = this.connectionForm.get('host')?.value;
    const port = this.connectionForm.get('port')?.value;
    const service = this.connectionForm.get('service')?.value;

    if (dbType && host && port && service) {
      let url = '';

      switch (dbType) {
        case 'ORACLE':
          url = `jdbc:oracle:thin:@//${host}:${port}/${service}`;
          break;
        case 'MYSQL':
          url = `jdbc:mysql://${host}:${port}/${service}`;
          break;
        case 'POSTGRESQL':
          url = `jdbc:postgresql://${host}:${port}/${service}`;
          break;
        case 'SQLSERVER':
          url = `jdbc:sqlserver://${host}:${port};databaseName=${service}`;
          break;
        default:
          url = '';
      }

      this.connectionForm.patchValue({ url }, { emitEvent: false });
    }
  }

  /**
   * Load all database connections from backend
   */
  private loadConnections() {
    this.loading.set(true);
    this.dbService.getAll().subscribe({
      next: (connections) => {
        // Store connections directly from backend
        this.connectionList = connections;
        this.loading.set(false);
      },
      error: (err) => {
        console.error('Error loading connections:', err);
        this.toastr.error('Failed to load connections from server', 'Error');
        this.loading.set(false);
      }
    });
  }

  /**
   * Open connection selection modal using new modal system
   */
  openConnectionModal() {
    console.log('Opening connection selection modal');

    // Reset modal state
    this.showModal.set(false);
    this.modalComponent = undefined;

    setTimeout(() => {
      // Import the connection selection modal component (we'll create this)
      import('../components/connection-selection-modal/connection-selection-modal').then(module => {
        this.modalComponent = module.ConnectionSelectionModalComponent;

        // Prepare modal data
        this.modalComponentData = {
          config: {
            title: 'Select Database Connection',
            searchPlaceholder: 'Search connections by name, type...',
            findButtonText: 'Search',
            loadingText: 'Searching connections...',
            noDataMessage: 'No connections found. Create a new connection first.',
            allowMultiSelect: false,
            showCreateNew: false
          }
        };

        console.log('Opening modal with data:', this.modalComponentData);
        this.showModal.set(true);
      }).catch(error => {
        console.error('Error loading connection modal:', error);
        this.toastr.error('Failed to load connection selection modal', 'Error');
      });
    }, 50);
  }

  /**
   * Handle modal result
   */
  onModalResult(result: any) {
    console.log('Modal result received:', result);

    if (!result) {
      this.showModal.set(false);
      return;
    }

    // Handle connection selection result
    if (result.id && result.connectionName) {
      // Map the selected connection to the new form structure
      this.connectionForm.patchValue({
        id: result.id,
        connectionName: result.connectionName,
        dbType: result.dbType || result.databaseType,
        host: result.host || this.extractHostFromAddress(result.dbServerAddress),
        port: result.port || this.extractPortFromAddress(result.dbServerAddress),
        service: result.service || result.databaseName,
        username: result.username,
        vAppName: result.vAppName || 'ultimus',
        appId: result.appId || 'ultimus',
        isDefaultConnection: result.isDefaultConnection,
        password: '' // Clear password for security
      });
    }

    this.showModal.set(false);
  }

  /**
   * Handle modal close
   */
  onModalClose() {
    this.showModal.set(false);
  }

  /**
   * Extract host from dbServerAddress (e.g., "192.168.1.100:1521" -> "192.168.1.100")
   */
  private extractHostFromAddress(address: string): string {
    if (!address) return '';
    const parts = address.split(':');
    return parts[0] || '';
  }

  /**
   * Extract port from dbServerAddress (e.g., "192.168.1.100:1521" -> "1521")
   */
  private extractPortFromAddress(address: string): string {
    if (!address) return '1521';
    const parts = address.split(':');
    return parts[1] || '1521';
  }

  /**
   * Custom validator for application name
   * Rules: No special characters except hyphen (-) and underscore (_), no spaces
   */
  private validateAppName(control: any) {
    if (!control.value) return null;

    const appName = control.value.toString();
    const validPattern = /^[a-zA-Z0-9_-]+$/;

    if (!validPattern.test(appName)) {
      return {
        invalidAppName: {
          message: 'Application name can only contain letters, numbers, hyphens (-), and underscores (_). No spaces or other special characters allowed.'
        }
      };
    }

    return null;
  }

  /**
   * Handle ID change - fetch connection if ID is valid
   */
  onIdChanged(value: string): void {
    const id = parseInt(value);

    // Only fetch if it's a valid number
    if (!isNaN(id) && id > 0) {
      this.loading.set(true);
      this.dbService.getById(id).subscribe({
        next: (connection: any) => {
          console.log('Loaded connection data:', connection);

          // Populate form with fetched connection (handle both old and new formats)
          this.connectionForm.patchValue({
            id: connection.id,
            vAppName: connection.vAppName || connection.v_app_name || 'ultimus',
            dbType: connection.dbType || connection.databaseType || 'ORACLE',
            driver: connection.driver || 'oracle.jdbc.OracleDriver',
            host: connection.host || this.extractHostFromAddress(connection.dbServerAddress),
            port: connection.port || this.extractPortFromAddress(connection.dbServerAddress),
            service: connection.service || connection.databaseName || '',
            url: connection.url || '',
            username: connection.username,
            connectionName: connection.connectionName,
            isDefaultConnection: connection.isDefaultConnection,
            password: '' // Clear password for security
          });

          // this.toastr.info('Connection loaded. Please enter password and verify details.', 'Connection Loaded');
          this.loading.set(false);
        },
        error: (err) => {
          console.error('Error loading connection:', err);
          // Don't show error toast for not found - user might be typing
          if (err.status === 404 || (err.error?.detail && err.error?.detail.includes("not found"))) {
            this.toastr.error('Connection not found!', 'Error');
          } else {
            this.toastr.error('Failed to load connection', 'Error');
          }
          this.loading.set(false);
          this.connectionForm.reset();
        }
      });
    }
  }

  /**
   * Save or update connection
   */
  onSave() {

    if (this.connectionForm.invalid) {
      this.toastr.error('Please fill all required fields correctly.', 'Validation Error');
      Object.keys(this.connectionForm.controls).forEach(key => {
        const control = this.connectionForm.get(key);
        if (control?.invalid) {
          console.log(`Invalid field: ${key}`, control.errors);
          control.markAsTouched();
        }
      });
      return;
    }
    this._authService.userInfo("token");
    this.loading.set(true);
    const userId = this._userService?.user?.username??'admin';

    const vAppNameValue = this.connectionForm.get('vAppName')?.value;

    const dto: any = {
      id: this.connectionForm.value.id || undefined,
      vAppName: vAppNameValue || 'ultimus',
      appId: environment.appId,
      dbType: this.connectionForm.value.dbType,
      driver: this.connectionForm.value.driver,
      host: this.connectionForm.value.host,
      port: this.connectionForm.value.port,
      service: this.connectionForm.value.service,
      url: this.connectionForm.value.url,
      username: this.connectionForm.value.username,
      password: this.connectionForm.value.password,
      connectionName: this.connectionForm.value.connectionName,
      isDefaultConnection: this.connectionForm.value.isDefaultConnection,
      modifyBy: userId,
      modifiedDate: new Date().toISOString(),
    };

    // Check if updating existing or creating new
    const isUpdate = dto.id && dto.id > 0;

    if (isUpdate) {
      // Update existing
      this.dbService.update(dto.id!, dto).subscribe({
        next: (result) => {
          this.toastr.success('Connection updated successfully!', 'Success');
          this.loadConnections();
          this.loading.set(false);
        },
        error: (err) => {
          console.error('Error updating connection:', err);
          this.toastr.error('Failed to update connection', 'Error');
          this.loading.set(false);
        }
      });
    } else {
      dto.createdBy= userId;
      dto.createdDate = new Date().toISOString();
      // Create new
      this.dbService.create(dto).subscribe({
        next: (result) => {
          this.toastr.success('Connection created successfully!', 'Success');
          this.loadConnections();
          this.connectionForm.reset({
            id: null,
            vAppName: 'ultimus',
            dbType: 'ORACLE',
            driver: 'oracle.jdbc.OracleDriver',
            port: '1521',
            isDefaultConnection: false,
          });
          this.loading.set(false);
          this.onClickSave.set(false);
        },
        error: (err) => {
          console.error('Error creating connection:', err);
          this.toastr.error('Failed to create connection', 'Error');
          this.loading.set(false);
          this.onClickSave.set(false);
        }
      });
    }

    this.onClickSave.set(false);

  }

  /**
   * Refresh/reset form
   */
  onRefresh() {
    this.connectionForm.reset({
      vAppName: 'ultimus',
      dbType: 'ORACLE',
      driver: 'oracle.jdbc.OracleDriver',
      port: '1521',
      isDefaultConnection: false,
    });
    this.onClickReset.set(false);
  }

  /**
   * Test database connection
   */
  onTestConnection() {
    if (this.connectionForm.get('dbServerAddress')?.invalid ||
        this.connectionForm.get('userName')?.invalid ||
        this.connectionForm.get('password')?.invalid) {
      this.toastr.error('Please provide server address, username, and password to test connection.', 'Validation Error');
      return;
    }

    this.loading.set(true);

    const dto: any = {
      id: this.connectionForm.value.id || undefined,
      vAppName: this.connectionForm.value.vAppName,
      dbType: this.connectionForm.value.dbType,
      driver: this.connectionForm.value.driver,
      host: this.connectionForm.value.host,
      port: this.connectionForm.value.port,
      service: this.connectionForm.value.service,
      url: this.connectionForm.value.url,
      username: this.connectionForm.value.username,
      password: this.connectionForm.value.password,
      connectionName: this.connectionForm.value.connectionName,
      isDefaultConnection: this.connectionForm.value.isDefaultConnection,
    };

    this.dbService.testConnection(dto).subscribe({
      next: (success) => {
        this.loading.set(false);
        if (success) {
          this.toastr.success('Database connection test successful!', 'Connection Test');
        } else {
          this.toastr.error('Failed to connect to database. Please check your credentials and server address.', 'Connection Test Failed');
        }
      },
      error: (err) => {
        console.error('Error testing connection:', err);
        this.toastr.error('Connection test failed. Please check your configuration.', 'Connection Test Failed');
        this.loading.set(false);
      }
    });
  }
}
