# =================================
# Application & Server Configuration
# =================================
spring.application.name=sandbox
spring.threads.virtual.enabled=true
server.port=8199

# =======================================
# Request Mapping / API (Path) Versioning
# =======================================
server.servlet.context-path=/sandbox

# ===============================
# Security / OAuth2 Configuration
# ===============================
security.enabled=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://192.168.10.56:9080/realms/MicroCube_dev

# ====================
# Resource-manager url
# ====================
#resource.manager.base-url=http://localhost:9999

# =======================================================
# Oracle Database Configuration
# =======================================================
spring.datasource.url=jdbc:oracle:thin:@//192.168.20.76:1521/buprim
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=playground
spring.datasource.password=pg

# ==============================
# JPA / Hibernate Configuration
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.hbm2ddl.halt_on_error=false
spring.jpa.properties.hibernate.default_schema=playground

# ====================================
# HikariCP Connection Pool
# ====================================
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=2000000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.pool-name=HikariPool

# =====================
# Logging Configuration
# =====================
logging.level.org.hibernate.SQL=error
logging.level.org.hibernate.orm.jdbc.jdbcbind=TRACE

# ====================
# Microcube Mocking
# ====================
microcube.mocking.enabled=false
microcube.mocking.data=10

# ====================
# Microcube Logging
# ====================
microcube.logging.host=localhost
microcube.logging.port=5000
microcube.logging.level=DEBUG

# ====================
# Microcube Messaging
# ====================
microcube.messaging.enabled=false
microcube.messaging.interval=1000
microcube.messaging.retry=5

# ==============================
# Eureka Discovery Configuration
# ==============================
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://192.168.10.56:8761/eureka/


# my config
logging.level.org.hibernate.engine.transaction.jta.platform.internal=ERROR