import { CommonModule } from '@angular/common';
import { Component, OnInit, WritableSignal, effect, inject, signal } from '@angular/core';
import {
  FormBuilder,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { MatIconModule } from '@angular/material/icon';
import { MatTooltipModule } from '@angular/material/tooltip';
import { ToastrService } from 'ngx-toastr';
import { ApiEndpointService, ApiEndpointDTO } from '../services/api-endpoint.service';
import { DialogUtils } from '../../../service/dialog-utils';
import { BUTTON_VISIBILITY, MENU_NAME, ONCLICK_RESET, ONCLICK_SAVE } from '../../../constant/button-signals.constant';
import { InputTextBox } from '../../../common-components/input-types/input-text-box/input-text-box';
import { InputSelectOptionField } from '../../../common-components/input-types/input-select-option-field/input-select-option-field';
import { GenericButton } from '../../../common-components/generic-component-type/generic-button/generic-button';
import { ExpansionPanelHeader } from '../../../common-components/expansion-panel-header/expansion-panel-header';
import { InputNumber } from '../../../common-components/input-types/input-number/input-number';
import { InputTextArea } from '../../../common-components/input-types/input-text-area/input-text-area';
import { UserService } from '../../../../core/user/user.service';


/**
 * API Endpoint Setup Page
 * Handles CRUD operations for API endpoint configurations
 */
@Component({
  selector: 'app-report-api-setup-ui',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatIconModule,
    MatTooltipModule,
    InputTextBox,
    InputSelectOptionField,
    GenericButton,
    ExpansionPanelHeader,
    InputTextArea,
    InputNumber
  ],
  templateUrl: './report-api-setup-ui.html',
  styleUrl: './report-api-setup-ui.scss'
})
export class ReportApiSetupUI implements OnInit {
  // Injected services
  private formBuilder = inject(FormBuilder);
  private toastr = inject(ToastrService);
  private dialogUtils = inject(DialogUtils);
  private apiService = inject(ApiEndpointService);
  private _userService = inject(UserService);
  // Form and state properties
  endpointForm!: FormGroup;
  loading = signal<boolean>(false);
  apiEndpointPanel: WritableSignal<boolean> = signal(true);

  // HTTP Method options
  httpMethodOptions = [
    { key: 'GET', value: 'GET' },
    { key: 'POST', value: 'POST' },
    { key: 'PUT', value: 'PUT' },
    { key: 'DELETE', value: 'DELETE' },
  ];

  // Authentication Type options
  authenticationTypeOptions = [
    { key: 'NONE', value: 'None' },
    { key: 'APPTOKEN', value: 'App Token' },
    { key: 'BASIC', value: 'Basic Auth' },
    { key: 'BEARER', value: 'Bearer Token' },
    { key: 'APIKEY', value: 'API Key' },
  ];

  // Endpoint list loaded from backend
  endpointList: ApiEndpointDTO[] = [];

  menuName = MENU_NAME;
  onClickReset = ONCLICK_RESET;
  onClickSave = ONCLICK_SAVE;

  constructor() {
    effect(() => {
      let localMenuName = 'API ENDPOINT SETUP';
      this.menuName.set(localMenuName);
    });
    BUTTON_VISIBILITY.set({
      save: true,
      update: false,
      view: false,
      delete: false,
      exit: false,
      reset: true,
    });
    this.setupSignalEffects();
  }

  ngOnInit() {
    this.initializeForm();
    this.setupAuthTypeListener();
    this.loadEndpoints();
  }

  private setupSignalEffects(): void {
    effect(() => {
      this.handleButtonActions();
    });
  }

  private handleButtonActions(): void {
    if (this.onClickReset()) {
      this.onRefresh();
    } else if (this.onClickSave()) {
      this.onSave();
    }
  }

  /**
   * Initialize the endpoint form with validation
   */
  private initializeForm() {
    this.endpointForm = this.formBuilder.group({
      id: [null], // Auto-generated by backend
      endpointName: ['', [Validators.required, Validators.maxLength(100)]],
      endpointUrl: ['', [Validators.required, Validators.maxLength(500), Validators.pattern(/^https?:\/\/.+/)]],
      httpMethod: ['GET', [Validators.required]],
      authenticationType: ['NONE', [Validators.required]],
      authUsername: [''],
      authPassword: [''],
      authToken: [''],
      headers: [''],
      timeout: [30, [Validators.required, Validators.min(5), Validators.max(300)]],
      isDefaultEndpoint: [false],
    });
  }

  /**
   * Setup listener for authentication type changes to show/hide credential fields
   */
  private setupAuthTypeListener() {
    this.endpointForm.get('authenticationType')?.valueChanges.subscribe(authType => {
      this.updateAuthValidators(authType);
    });
  }

  /**
   * Update validators based on authentication type
   */
  private updateAuthValidators(authType: string) {
    const usernameControl = this.endpointForm.get('authUsername');
    const passwordControl = this.endpointForm.get('authPassword');
    const tokenControl = this.endpointForm.get('authToken');

    // Clear all validators first
    usernameControl?.clearValidators();
    passwordControl?.clearValidators();
    tokenControl?.clearValidators();

    // Set validators based on auth type
    if (authType === 'BASIC') {
      usernameControl?.setValidators([Validators.required, Validators.maxLength(50)]);
      passwordControl?.setValidators([Validators.required, Validators.minLength(6)]);
    } else if (authType === 'BEARER' || authType === 'APIKEY') {
      tokenControl?.setValidators([Validators.required, Validators.maxLength(200)]);
    }

    // Update validity
    usernameControl?.updateValueAndValidity();
    passwordControl?.updateValueAndValidity();
    tokenControl?.updateValueAndValidity();
  }

  /**
   * Check if authentication credentials should be shown
   */
  showAuthCredentials(): boolean {
    const authType = this.endpointForm.get('authenticationType')?.value;
    return authType !== 'NONE';
  }

  /**
   * Check if Basic Auth fields should be shown
   */
  showBasicAuth(): boolean {
    return this.endpointForm.get('authenticationType')?.value === 'BASIC';
  }

  /**
   * Check if Token field should be shown
   */
  showTokenAuth(): boolean {
    const authType = this.endpointForm.get('authenticationType')?.value;
    return authType === 'BEARER' || authType === 'APIKEY';
  }

  /**
   * Load all API endpoints from backend
   */
  private loadEndpoints() {
    this.loading.set(true);
    this.apiService.getAll().subscribe({
      next: (endpoints) => {
        // Store endpoints directly from backend
        this.endpointList = endpoints;
        this.loading.set(false);
      },
      error: (err) => {
        console.error('Error loading endpoints:', err);
        this.toastr.error('Failed to load endpoints from server', 'Error');
        this.loading.set(false);
      }
    });
  }

  /**
   * Handle ID change - fetch endpoint if ID is valid
   */
  onIdChanged(value: string): void {
    const id = parseInt(value);

    // Only fetch if it's a valid number
    if (!isNaN(id) && id > 0) {
      this.loading.set(true);
      this.apiService.getById(id).subscribe({
        next: (endpoint) => {
          // Populate form with fetched endpoint
          this.endpointForm.patchValue({
            id: endpoint.id,
            endpointName: endpoint.endpointName,
            endpointUrl: endpoint.endpointUrl,
            httpMethod: endpoint.httpMethod,
            authenticationType: endpoint.authenticationType,
            authUsername: endpoint.authUsername,
            authToken: endpoint.authToken,
            headers: endpoint.headers,
            timeout: endpoint.timeout,
            isDefaultEndpoint: endpoint.isDefaultEndpoint,
            authPassword: '' // Clear password for security
          });
          this.toastr.info('Endpoint loaded. Please enter credentials and verify details.', 'Endpoint Loaded');
          this.loading.set(false);
        },
        error: (err) => {
          console.error('Error loading endpoint:', err);
          // Don't show error toast for not found
          if (err.status !== 404) {
            this.toastr.error('Failed to load endpoint', 'Error');
          }
          this.loading.set(false);
        }
      });
    }
  }



  onIdBoxChanged(value: string): void {
    console.log('IdBox changed:', value);
  }

  /**
   * Save or update endpoint
   */
  onSave() {
    if (this.endpointForm.invalid) {
      this.toastr.error('Please fill all required fields correctly.', 'Validation Error');
      Object.keys(this.endpointForm.controls).forEach(key => {
        const control = this.endpointForm.get(key);
        if (control?.invalid) {
          control.markAsTouched();
        }
      });
      return;
    }

    this.loading.set(true);
    const userId = this._userService?.user?.username??'admin';
    const dto: ApiEndpointDTO = {
      id: this.endpointForm.value.id || undefined,
      endpointName: this.endpointForm.value.endpointName,
      endpointUrl: this.endpointForm.value.endpointUrl,
      httpMethod: this.endpointForm.value.httpMethod,
      authenticationType: this.endpointForm.value.authenticationType,
      authUsername: this.endpointForm.value.authUsername,
      authPassword: this.endpointForm.value.authPassword,
      authToken: this.endpointForm.value.authToken,
      headers: this.endpointForm.value.headers,
      timeout: this.endpointForm.value.timeout,
      isDefaultEndpoint: this.endpointForm.value.isDefaultEndpoint,
      modifyBy: userId,
      modifiedDate: new Date().toISOString(),
    };

    // Check if updating existing or creating new
    const isUpdate = dto.id && dto.id > 0;

    if (isUpdate) {
      // Update existing
      this.apiService.update(dto.id!, dto).subscribe({
        next: (result) => {
          this.toastr.success('Endpoint updated successfully!', 'Success');
          this.loadEndpoints();
          this.loading.set(false);
        },
        error: (err) => {
          console.error('Error updating endpoint:', err);
          this.toastr.error('Failed to update endpoint', 'Error');
          this.loading.set(false);
        }
      });
    } else {
      dto.createdBy= userId;
      dto.createdDate = new Date().toISOString();
      // Create new
      this.apiService.create(dto).subscribe({
        next: (result) => {
          this.toastr.success('Endpoint created successfully!', 'Success');
          this.loadEndpoints();
          this.endpointForm.reset({
            id: null,
            httpMethod: 'GET',
            authenticationType: 'NONE',
            timeout: 30,
            isDefaultEndpoint: false,
          });
          this.loading.set(false);
          this.onClickSave.set(false);
        },
        error: (err) => {
          console.error('Error creating endpoint:', err);
          this.toastr.error('Failed to create endpoint', 'Error');
          this.loading.set(false);
          this.onClickSave.set(false);
        }
      });
    }
    this.onClickSave.set(false);
  }

  /**
   * Refresh/reset form
   */
  onRefresh() {
    this.endpointForm.reset({
      httpMethod: 'GET',
      authenticationType: 'NONE',
      timeout: 30,
      isDefaultEndpoint: false,
    });
    this.onClickReset.set(false);
    this.toastr.info('Form has been reset.', 'Refresh');
  }

  /**
   * Test endpoint connection
   */
  onTestEndpoint() {
    if (this.endpointForm.get('endpointUrl')?.invalid) {
      this.toastr.error('Please provide a valid endpoint URL to test.', 'Validation Error');
      return;
    }

    this.loading.set(true);

    const dto: ApiEndpointDTO = {
      id: this.endpointForm.value.id || undefined,
      endpointName: this.endpointForm.value.endpointName,
      endpointUrl: this.endpointForm.value.endpointUrl,
      httpMethod: this.endpointForm.value.httpMethod,
      authenticationType: this.endpointForm.value.authenticationType,
      authUsername: this.endpointForm.value.authUsername,
      authPassword: this.endpointForm.value.authPassword,
      authToken: this.endpointForm.value.authToken,
      headers: this.endpointForm.value.headers,
      timeout: this.endpointForm.value.timeout,
      isDefaultEndpoint: this.endpointForm.value.isDefaultEndpoint,
    };

    this.apiService.testEndpoint(dto).subscribe({
      next: (success) => {
        this.loading.set(false);
        if (success) {
          this.toastr.success('Endpoint connection test successful!', 'Connection Test');
        } else {
          this.toastr.error('Failed to connect to endpoint. Please check your URL and credentials.', 'Connection Test Failed');
        }
      },
      error: (err) => {
        console.error('Error testing endpoint:', err);
        this.toastr.error('Connection test failed. Please check your configuration.', 'Connection Test Failed');
        this.loading.set(false);
      }
    });
  }
}
